name: Blank Workflow
on: [push, pull_request, workflow_dispatch]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, World!"
  
  tests1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test after build
        run: echo "after build"
  
  tests2:
    runs-on: ubuntu latest
    steps:
      - name: test in parallel with build
        run: echo "parallel with build"